"""providers models usage

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 17:45:18.689421
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("api_key_secret_id", sa.UUID(), nullable=True),
        sa.Column("headers_secret_id", sa.UUID(), nullable=True),
        sa.Column("header_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_secret_id"],
            ["secrets.id"],
            name=op.f("fk_providers_api_key_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["headers_secret_id"],
            ["secrets.id"],
            name=op.f("fk_providers_headers_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
    )
    op.create_table(
        "models",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("model_key", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("max_output", sa.Integer(), nullable=True),
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provider_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_models_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint(
            "provider_id", "model_key", name=op.f("uq_models_provider_id_model_key")
        ),
    )
    op.create_index(op.f("ix_models_provider_id"), "models", ["provider_id"], unique=False)
    op.create_table(
        "usage_records",
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("model_key", sa.String(length=200), nullable=False),
        sa.Column("request_kind", sa.String(length=30), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("automation_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cost_source", sa.String(length=12), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_usage_records_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_usage_records_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index("ix_usage_records_model_ts", "usage_records", ["model_id", "ts"], unique=False)
    op.create_index(op.f("ix_usage_records_run_id"), "usage_records", ["run_id"], unique=False)
    op.create_index("ix_usage_records_ts", "usage_records", ["ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_records_ts", table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_run_id"), table_name="usage_records")
    op.drop_index("ix_usage_records_model_ts", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_models_provider_id"), table_name="models")
    op.drop_table("models")
    op.drop_table("providers")
    # ### end Alembic commands ###
