"""run file changes

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-30 20:09:40.939732
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_file_changes",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("tool_call_id", sa.UUID(), nullable=True),
        sa.Column("op", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("dest_path", sa.String(length=1000), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("backup_ref", sa.String(length=200), nullable=True),
        sa.Column("reverted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_file_changes_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
            name=op.f("fk_run_file_changes_tool_call_id_tool_calls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_file_changes")),
    )
    op.create_index(
        "ix_run_file_changes_run", "run_file_changes", ["run_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_file_changes_run", table_name="run_file_changes")
    op.drop_table("run_file_changes")
    # ### end Alembic commands ###
