"""profiles skills pause

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 23:20:39.331594
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("required_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("slug", name=op.f("uq_skills_slug")),
    )
    op.create_table(
        "agent_profiles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("default_model_id", sa.UUID(), nullable=True),
        sa.Column("permission_levels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("plan_review", sa.String(length=10), nullable=True),
        sa.Column("skill_mode", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_model_id"],
            ["models.id"],
            name=op.f("fk_agent_profiles_default_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_agent_profiles_name")),
    )
    op.create_table(
        "profile_skills",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["agent_profiles.id"],
            name=op.f("fk_profile_skills_profile_id_agent_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_profile_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", "skill_id", name=op.f("pk_profile_skills")),
    )
    op.add_column(
        "approvals",
        sa.Column("kind", sa.String(length=10), server_default="action", nullable=False),
    )
    op.add_column("conversations", sa.Column("profile_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_conversations_profile_id_agent_profiles"),
        "conversations",
        "agent_profiles",
        ["profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "runs", sa.Column("pause_requested", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("runs", sa.Column("profile_id", sa.UUID(), nullable=True))
    op.add_column(
        "runs", sa.Column("plan_version", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_runs_profile_id_agent_profiles"),
        "runs",
        "agent_profiles",
        ["profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_profile_id_agent_profiles"), "runs", type_="foreignkey")
    op.drop_column("runs", "plan_version")
    op.drop_column("runs", "profile_id")
    op.drop_column("runs", "pause_requested")
    op.drop_constraint(
        op.f("fk_conversations_profile_id_agent_profiles"), "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "profile_id")
    op.drop_column("approvals", "kind")
    op.drop_table("profile_skills")
    op.drop_table("agent_profiles")
    op.drop_table("skills")
    # ### end Alembic commands ###
