"""notifications and automations

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-01 04:34:45.773394
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_created", "notifications", ["created_at"], unique=False)
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "notification_destinations",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("secret_id", sa.UUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("kinds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["secrets.id"],
            name=op.f("fk_notification_destinations_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_destinations")),
        sa.UniqueConstraint("name", name=op.f("uq_notification_destinations_name")),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["notification_destinations.id"],
            name=op.f("fk_notification_deliveries_destination_id_notification_destinations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_deliveries_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    op.create_index(
        "ix_notification_deliveries_notification",
        "notification_deliveries",
        ["notification_id"],
        unique=False,
    )
    op.create_table(
        "automations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("on_ask", sa.String(length=10), nullable=False),
        sa.Column("notify", sa.String(length=12), nullable=False),
        sa.Column("destination_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("document_path", sa.String(length=300), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=12), nullable=True),
        sa.Column("last_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_automations_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["agent_profiles.id"],
            name=op.f("fk_automations_profile_id_agent_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
    )
    op.create_index(
        "ix_automations_due",
        "automations",
        ["next_run_at"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.add_column("conversations", sa.Column("automation_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_conversations_automation_id"), "conversations", ["automation_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_conversations_automation_id_automations"),
        "conversations",
        "automations",
        ["automation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("runs", sa.Column("automation_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_runs_automation_id"), "runs", ["automation_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_runs_automation_id_automations"),
        "runs",
        "automations",
        ["automation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_automation_id_automations"), "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_automation_id"), table_name="runs")
    op.drop_column("runs", "automation_id")
    op.drop_constraint(
        op.f("fk_conversations_automation_id_automations"), "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_conversations_automation_id"), table_name="conversations")
    op.drop_column("conversations", "automation_id")
    op.drop_index(
        "ix_automations_due", table_name="automations", postgresql_where=sa.text("enabled")
    )
    op.drop_table("automations")
    op.drop_index("ix_notification_deliveries_notification", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("notification_destinations")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_created", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
