"""mcp servers and tools

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-01 05:27:24.456613
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_servers",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("slug", sa.String(length=24), nullable=False),
        sa.Column("transport", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("command", sa.String(length=500), nullable=True),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("headers_secret_id", sa.UUID(), nullable=True),
        sa.Column("env_secret_id", sa.UUID(), nullable=True),
        sa.Column("header_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("env_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["env_secret_id"],
            ["secrets.id"],
            name=op.f("fk_mcp_servers_env_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["headers_secret_id"],
            ["secrets.id"],
            name=op.f("fk_mcp_servers_headers_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_servers")),
        sa.UniqueConstraint("name", name=op.f("uq_mcp_servers_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_mcp_servers_slug")),
    )
    op.create_table(
        "mcp_tools",
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("annotations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("permission", sa.String(length=10), nullable=True),
        sa.Column("risk_override", sa.String(length=10), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mcp_servers.id"],
            name=op.f("fk_mcp_tools_server_id_mcp_servers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tools")),
        sa.UniqueConstraint("server_id", "name", name=op.f("uq_mcp_tools_server_id_name")),
    )
    op.create_index(op.f("ix_mcp_tools_server_id"), "mcp_tools", ["server_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mcp_tools_server_id"), table_name="mcp_tools")
    op.drop_table("mcp_tools")
    op.drop_table("mcp_servers")
    # ### end Alembic commands ###
