"""sub-agent runs

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-01 13:14:38.685910
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("parent_run_id", sa.UUID(), nullable=True))
    op.add_column("runs", sa.Column("root_run_id", sa.UUID(), nullable=True))
    op.add_column("runs", sa.Column("depth", sa.Integer(), server_default="0", nullable=False))
    op.create_index(op.f("ix_runs_parent_run_id"), "runs", ["parent_run_id"], unique=False)
    op.create_index(op.f("ix_runs_root_run_id"), "runs", ["root_run_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_runs_parent_run_id_runs"),
        "runs",
        "runs",
        ["parent_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # The index of active runs also covers runs that wait for a sub-agent (Alembic
    # does not notice a changed index condition, hence by hand).
    op.drop_index("ix_runs_active", table_name="runs")
    op.create_index(
        "ix_runs_active",
        "runs",
        ["status"],
        unique=False,
        postgresql_where=sa.text(
            "status IN ('queued','running','paused','waiting_approval','waiting_subagent')"
        ),
    )


def downgrade() -> None:
    op.drop_index("ix_runs_active", table_name="runs")
    op.create_index(
        "ix_runs_active",
        "runs",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued','running','paused','waiting_approval')"),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_parent_run_id_runs"), "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_root_run_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_parent_run_id"), table_name="runs")
    op.drop_column("runs", "depth")
    op.drop_column("runs", "root_run_id")
    op.drop_column("runs", "parent_run_id")
    # ### end Alembic commands ###
