"""projects as workspaces and chat organisation

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-02 11:36:40.647785
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendar_events", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_index("ix_calendar_events_project", "calendar_events", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_calendar_events_project_id_projects"),
        "calendar_events",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("conversations", sa.Column("project_id", sa.UUID(), nullable=True))
    op.add_column(
        "conversations",
        sa.Column(
            "tags", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("conversations", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "conversations", sa.Column("summary_seq", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("conversations", sa.Column("branched_from_id", sa.UUID(), nullable=True))
    op.create_index("ix_conversations_project", "conversations", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_conversations_branched_from_id_conversations"),
        "conversations",
        "conversations",
        ["branched_from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_conversations_project_id_projects"),
        "conversations",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # Existing projects get a folder name made from their name ("My Thesis" -> "my-thesis");
    # a second project that would get the same one has part of its id added.
    op.add_column("projects", sa.Column("slug", sa.String(length=80), nullable=True))
    op.execute(
        """
        WITH named AS (
            SELECT id,
                   COALESCE(NULLIF(left(trim(both '-' from
                       regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')), 60), ''), 'project') AS base
            FROM projects
        ), numbered AS (
            SELECT id, base, row_number() OVER (PARTITION BY base ORDER BY id) AS n FROM named
        )
        UPDATE projects AS p
        SET slug = CASE WHEN numbered.n = 1 THEN numbered.base
                        ELSE numbered.base || '-' || left(p.id::text, 6) END
        FROM numbered
        WHERE numbered.id = p.id
        """
    )
    op.alter_column("projects", "slug", nullable=False)
    op.add_column(
        "projects", sa.Column("instructions", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("projects", sa.Column("default_model_id", sa.UUID(), nullable=True))
    op.add_column("projects", sa.Column("default_profile_id", sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f("uq_projects_slug"), "projects", ["slug"])
    op.create_foreign_key(
        op.f("fk_projects_default_model_id_models"),
        "projects",
        "models",
        ["default_model_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_projects_default_profile_id_agent_profiles"),
        "projects",
        "agent_profiles",
        ["default_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_default_profile_id_agent_profiles"), "projects", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_projects_default_model_id_models"), "projects", type_="foreignkey")
    op.drop_constraint(op.f("uq_projects_slug"), "projects", type_="unique")
    op.drop_column("projects", "default_profile_id")
    op.drop_column("projects", "default_model_id")
    op.drop_column("projects", "instructions")
    op.drop_column("projects", "slug")
    op.drop_constraint(
        op.f("fk_conversations_project_id_projects"), "conversations", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_conversations_branched_from_id_conversations"), "conversations", type_="foreignkey"
    )
    op.drop_index("ix_conversations_project", table_name="conversations")
    op.drop_column("conversations", "branched_from_id")
    op.drop_column("conversations", "summary_seq")
    op.drop_column("conversations", "summary")
    op.drop_column("conversations", "tags")
    op.drop_column("conversations", "project_id")
    op.drop_constraint(
        op.f("fk_calendar_events_project_id_projects"), "calendar_events", type_="foreignkey"
    )
    op.drop_index("ix_calendar_events_project", table_name="calendar_events")
    op.drop_column("calendar_events", "project_id")
    # ### end Alembic commands ###
